#!/bin/bash

case "$1" in

build)
   python3 logiabuild.py
   ;;

serve)
   python3 -m http.server 8000
   ;;

publish)
   DATE=$(date "+%Y-%m-%d %H:%M")
   python3 logiabuild.py || exit 1
   git add .
   git commit -m "Update LOGIA Homepage Build $DATE"
   git push
   ;;

clean)

   python3 -c "
from pathlib import Path
p = Path('$2')
p.write_text(
   p.read_text(encoding='utf-8').replace('\ufeff', ''),
   encoding='utf-8'
)
"
   ;;

*)
   echo ""
   echo "LOGIA"
   echo ""
   echo "Usage"
   echo "  ./logia build"
   echo "  ./logia serve"
   echo "  ./logia publish"
   echo "  ./logia clean"
   ;;
esac

