#!/bin/bash

case "$1" in

build)
   python3 logiabuild.py
   ;;

serve)
   python3 -m http.server 8000
   ;;

publish)
   DATE=$(date "+%Y-%m-%d %H:%M")
   python3 logiabuild.py || exit 1
   git add .
   git commit -m "Update LOGIA Hompage Build $DATE"
   git push
   ;;

*)
   echo ""
   echo "LOGIA"
   echo ""
   echo "Usage"
   echo "  ./logia build"
   echo "  ./logia serve"
   echo "  ./logia publish"
   ;;
esac

